-- == BAGIAN 1: TABLE USERS (Untuk Login/Register & Saldo) ==
alter table users enable row level security;

drop policy if exists "Public Read Users" on users;
drop policy if exists "Public Insert Users" on users;
drop policy if exists "Public Update Users" on users;

create policy "Public Read Users" on users for select using (true);
create policy "Public Insert Users" on users for insert with check (true);
create policy "Public Update Users" on users for update using (true);


-- == BAGIAN 2: TABLE PRODUCTS (Untuk Sinkronisasi Produk) ==
alter table products enable row level security;

drop policy if exists "Public Read Products" on products;
drop policy if exists "Public Insert Products" on products;
drop policy if exists "Public Update Products" on products;
drop policy if exists "Public Delete Products" on products;

create policy "Public Read Products" on products for select using (true);
create policy "Public Insert Products" on products for insert with check (true);
create policy "Public Update Products" on products for update using (true);
create policy "Public Delete Products" on products for delete using (true);


-- == BAGIAN 3: TABLE ORDERS (Untuk Transaksi Pembelian) ==
alter table orders enable row level security;

drop policy if exists "Public Read Orders" on orders;
drop policy if exists "Public Insert Orders" on orders;
drop policy if exists "Public Update Orders" on orders;

create policy "Public Read Orders" on orders for select using (true);
create policy "Public Insert Orders" on orders for insert with check (true);
create policy "Public Update Orders" on orders for update using (true);


-- == BAGIAN 4: TABLE INFORMATION_BOARD (Untuk Papan Pengumuman) ==
create table if not exists information_board (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  type text default 'info', -- 'info', 'warning', 'urgent', 'success'
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table information_board enable row level security;

drop policy if exists "Public Read InfoBoard" on information_board;
drop policy if exists "Public Manage InfoBoard" on information_board;

create policy "Public Read InfoBoard" on information_board for select using (true);
create policy "Public Manage InfoBoard" on information_board for all using (true) with check (true);

-- Data Dummy Info
insert into information_board (title, content, type, is_active)
select 'Selamat Datang', 'Selamat datang di Vanness Store! Nikmati layanan OTP termurah.', 'success', true
where not exists (select 1 from information_board);


-- == BAGIAN 5: TABLE VOUCHERS (Untuk Topup Saldo via Kode) ==
create table if not exists vouchers (
  id bigint generated by default as identity primary key,
  code text not null unique,
  amount numeric not null,
  is_used boolean default false,
  used_by uuid references auth.users(id), -- Optional: track who used it
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table vouchers enable row level security;

drop policy if exists "Public Read Vouchers" on vouchers;
drop policy if exists "Public Manage Vouchers" on vouchers;

create policy "Public Read Vouchers" on vouchers for select using (true);
create policy "Public Manage Vouchers" on vouchers for all using (true) with check (true);

-- Data Dummy Voucher (Kode: WELCOME10K)
insert into vouchers (code, amount, is_used)
select 'WELCOME10K', 10000, false
where not exists (select 1 from vouchers where code = 'WELCOME10K');
