-- Run this SQL in your Supabase SQL Editor or Dashboard

-- 1. Table for Information/Announcement Board
create table if not exists public.information_board (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  type text not null check (type in ('info', 'warning', 'success', 'urgent')),
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) - Optional but recommended
alter table public.information_board enable row level security;

-- Policy to allow read access to everyone
create policy "Public board are viewable by everyone"
  on public.information_board for select
  using ( true );

-- Policy to allow insert/update/delete only by service_role or specific logic (adjust as needed)
-- For now allowing all for simplicity of the dashboard if RLS is enabled, 
-- or you can disable RLS if you handle auth in app logic solely.
create policy "Enable all access for all users"
  on public.information_board for all
  using ( true )
  with check ( true );


-- ========================================================
-- OPTIONAL: Ensure other tables exist if not already created
-- ========================================================

-- 2. Users Table (Custom Auth)
create table if not exists public.users (
  id uuid default gen_random_uuid() primary key,
  name text,
  email text unique not null,
  password text not null,
  role text default 'user',
  balance numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Users
alter table public.users enable row level security;
create policy "Users can view own data" on public.users for select using (auth.uid() = id); 
-- Note: Since you are using custom auth (not Supabase Auth), RLS based on auth.uid() won't work directly 
-- without custom headers. You might want to disable RLS for this table or use a broader policy 
-- if your API handles security.
-- OPEN POLICY FOR DEVELOPMENT (Secure this later!):
create policy "Enable all access for dev" on public.users for all using (true) with check (true);


-- 3. Products Table
create table if not exists public.products (
  id uuid default gen_random_uuid() primary key,
  platform text not null,
  country text not null,
  price numeric not null,
  stock integer default 0,
  icon text,
  flag text, 
  country_id text,
  service_code text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Products
alter table public.products enable row level security;
create policy "Public products are viewable by everyone" on public.products for select using (true);
create policy "Enable all access for dev" on public.products for all using (true) with check (true);
